version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: metro
      POSTGRES_USER: metro-user
      POSTGRES_PASSWORD: metropass
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"